### ISSUE TITLE
Installing outside of Rails may not be working?

### ISSUE THREAD

**Issue by science** [jackc/edge#10]
I'm trying to use Edge outside of Rails. I love the idea. I'm having trouble getting all the features to work. Some of them work which makes me think the problem is that I'm running AR outside of Rails.

For example I can run ".find_forest" and get back the root of my forest. But when I run ".with_descendents" I get back `NoMethodError: undefined method 'with_descendents' for #<Tag::ActiveRecord_Relation:0x007fd06bd2d690>`.

I have an AR class "Tag" which has the "acts_as_forest" directive in it. Tag has a "parent_id" integer field. But running code like

```
Tag.where(name: "Medical Care").with_descendents.all
```

Yields the NoMethodError above.

Any thoughts?

**Comment by jackc** [comment]
FYI, I released v0.4.0 with the current head revision.
