### ISSUE TITLE
Document/support ancestors method?

### ISSUE THREAD

**Issue by science** [jackc/edge#12]
We are relying on your ancestors (https://github.com/jackc/edge/blob/master/lib/edge/forest.rb#L145) method at this point. But it's not documented so maybe subject to change. Would you be willing to make that method a supported method?

If so, I can send you pull request with documentation update if that's useful to you.. Thanks.

**Comment by jackc** [comment]
Sure. I think that it is fair for that method to be considered supported.

**Comment by jackc** [comment]
Merged pull request 13.
