### ISSUE TITLE
PG::ProtocolViolation

### ISSUE THREAD

**Issue by hx** [jackc/edge#14]
Some have suggested <https://github.com/rails/rails/issues/20236> is caused by edge unscoping and re-binding values around <https://github.com/jackc/edge/blob/master/lib/edge/forest.rb#L97-L102>. Is there another way to achieve this?

**Comment by hx** [comment]
Closed by PR <https://github.com/jackc/edge/pull/15>

**Comment by TheKidCoder** [comment]
I am still running into this on jRuby. MRI seems to be fine though.
```
I am still setting this issue on jRuby.
```
[11] pry(main)> ActiveRecord.version
=> Gem::Version.new("4.2.5")
[12] pry(main)> exit
~reppro|rails4.2⚡ ⇒ rails c
Loading development environment (Rails 4.2.5)
[1] pry(main)> ActiveRecord.version
=> Gem::Version.new("4.2.5")
[2] pry(main)> Edge::VERSION
=> "0.4.3"
[3] pry(main)> Group.where(name: "Universal Questions").find_forest
   (21.0ms)  SELECT version()
  Group Load (10.0ms)  WITH RECURSIVE "all_nodes" AS ( SELECT "prompts"."id", "prompts"."parent_id" FROM "prompts" WHERE "prompts"."type" IN ('Group') AND "prompts"."name" = ? UNION SELECT "prompts"."id", "prompts"."parent_id" FROM "prompts" INNER JOIN "all_nodes" ON "prompts"."parent_id" = "all_nodes"."id" ) SELECT * FROM "all_nodes" INNER JOIN "prompts" ON "all_nodes"."id" = "prompts"."id"  ORDER BY position
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: bind message supplies 0 parameters, but prepared statement "" requires 1: WITH RECURSIVE "all_nodes" AS ( SELECT "prompts"."id", "prompts"."parent_id" FROM "prompts" WHERE "prompts"."type" IN ('Group') AND "prompts"."name" = ? UNION SELECT "prompts"."id", "prompts"."parent_id" FROM "prompts" INNER JOIN "all_nodes" ON "prompts"."parent_id" = "all_nodes"."id" ) SELECT * FROM "all_nodes" INNER JOIN "prompts" ON "all_nodes"."id" = "prompts"."id"  ORDER BY position
from arjdbc/jdbc/RubyJdbcConnection.java:888:in `execute_query'
[4] pry(main)>
```
```

**Comment by jackc** [comment]
I don't have a JRuby install handy at the moment. Do the tests pass on JRuby?

**Comment by jackc** [comment]
I installed JRuby and there are failing tests revealing this problem. It turns out that the MRI pg gem and JRuby's PostgreSQL adapter process bind variables at different times. It's a bit of a hack but edge now tries to detect JRuby and handle binds differently.

Just released v0.4.4 with the fix.

**Comment by TheKidCoder** [comment]
Awesome! Thanks, sorry I didn't see your earlier response.
